import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="es">
      <body className={inter.className}>
        <header>
          <h1 className='text-3xl bg-purple-700 text-white px-5 py-2'>Pokemon página</h1>
        </header>
        <main className='w-10/12 mx-auto mt-2'>
          {children}
        </main>
      </body>
    </html>
  )
}
